version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/etl_pipeline.log
    maxBytes: 10485760
    backupCount: 5

  errors:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: logs/errors.log
    maxBytes: 10485760
    backupCount: 5

loggers:
  src.biotech_pipeline:
    handlers: [console, file, errors]
    level: DEBUG
    propagate: false

root:
  handlers: [console]
  level: WARNING
