# CSS selectors or keyword heuristics for website scraping

team_section:
  headers: ["team", "leadership", "management", "founder"]
  tags: ["ul", "div.team-list", "section.team"]

advisors_section:
  headers: ["advisor", "mentor", "board"]
  tags: ["ul", "div.advisors-list", "section.advisors"]

products_section:
  headers: ["product", "service", "solution"]
  tags: ["ul", "div.products", "section.products"]
